### ISSUE TITLE
Nuevo Usuario

### ISSUE THREAD

**Issue by Marcods1980** [SparkleIMG/SparkleIMG.github.io#2]
**Primera opción (Obligatorio):**
MarcoD

**Segunda opción (Obligatorio):**
MarcoDS

**Tercera opción (Opcional):**
Ejemplo: Un-usuario

**HTML y CSS para página de usuario personalizada (opcional):**

**Comment by GabrielWasTaken** [comment]
Tu usuario ha sido creado con éxito.

Nombre de usuario: MarcoD
URL de usuario: sparkle.archmc.es/MarcoD

Gracias por usar SparkleIMG.
