### ISSUE TITLE
Subir Imagen

### ISSUE THREAD

**Issue by Marcods1980** [SparkleIMG/SparkleIMG.github.io#3]
**Imagen en formato PNG o JPG (obligatorio):**
![IMG_0312](https://github.com/user-attachments/assets/78ba63be-7aeb-4ee8-8588-1b6bd789f119)

**Comment by GabrielWasTaken** [comment]
Tu imagen se ha subido con éxito y está disponible en la URL sparkle.archmc.es/MarcoD/surf.png

Gracias por usar SparkleIMG.
