### ISSUE TITLE
Subir Imagen

### ISSUE THREAD

**Issue by Marcods1980** [SparkleIMG/SparkleIMG.github.io#4]
![IMG_7073](https://github.com/user-attachments/assets/8c0f9d6a-597c-4b5e-9d70-2ff68d146ad4)
**Imagen en formato PNG o JPG (obligatorio):**

**Comment by GabrielWasTaken** [comment]
Tu imagen se ha subido con éxito y está disponible en la URL sparkle.archmc.es/MarcoD/lluvia.jpeg

Gracias por usar SparkleIMG.
